name: Bug report
description: Report a bug.
title: '[Bug]: '
labels:
  - bug
body:
  - type: checkboxes
    id: '1'
    attributes:
      label: Preflight checklist
      description: Make sure you completed this before creating an issue.
      options:
        - label: >-
            I have searched the [issue
            tracker](https://github.com/ThaUnknown/miru/issues) for a bug report
            that matches the one I want to file, without success.
          required: true
        - label: >-
            I have searched the [frequently asked
            questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md)
            for a solution that fixes this problem, without success.
          required: true
        - label: >-
            I have checked that I'm using the [latest
            stable](https://github.com/ThaUnknown/miru/releases/latest) version
            of the app.
          required: true
  - type: input
    id: '2'
    attributes:
      label: What app version are you using?
      description: >-
        The app version you are currently using, you can view this at the bottom
        of the settings menu.
      placeholder: v2.0.1
    validations:
      required: true
  - type: dropdown
    id: '3'
    attributes:
      label: What operating system version are you using?
      options:
        - Windows
        - Linux
        - MacOS
    validations:
      required: true
  - type: textarea
    id: '4'
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
  - type: textarea
    id: '5'
    attributes:
      label: Actual Behavior
      description: A clear description of what actually happens.
    validations:
      required: true
  - type: textarea
    id: '6'
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
  - type: markdown
    attributes:
      value: >-
        This template was generated with [Issue Forms
        Creator](https://www.issue-forms-creator.app/)
