import SUPPORTS from './supports'

export default {
  volume: 1,
  playerAutoplay: true,
  playerAutoPiP: false,
  playerPause: true,
  playerAutocomplete: true,
  playerDeband: false,
  searchQuality: '1080',
  rssFeedsNew: SUPPORTS.isAndroid ? [['New Releases', 'SubsPlease']] : [],
  searchAutoSelect: true,
  searchBatch: true,
  torrentSpeed: 5,
  torrentPersist: false,
  torrentDHT: false,
  torrentPeX: false,
  torrentPort: 0,
  torrentStreamedDownload: true,
  dhtPort: 0,
  missingFont: true,
  maxConns: 50,
  subtitleRenderHeight: SUPPORTS.isAndroid ? '720' : '0',
  subtitleLanguage: 'eng',
  audioLanguage: 'jpn',
  enableDoH: true,
  doHURL: 'https://cloudflare-dns.com/dns-query',
  disableSubtitleBlur: SUPPORTS.isAndroid,
  showDetailsInRPC: true,
  cards: 'small',
  torrentPath: '',
  angle: 'default',
  extensions: SUPPORTS.isAndroid ? ['anisearch'] : [],
  sources: {},
  enableExternal: false,
  playerPath: '',
  playerSeek: 2,
  playerSkip: false,
  playerSkipFiller: false
}
